### PR TITLE
Update execution script

### PR DESCRIPTION
**Pull request by iomaganaris**
- Added CLI options in the bulb3dtest.py to make the execution of the model more versatile from the command line
- Updated mod files to be usable with NEURON and CoreNEURON after latest changes to psolve-direct
- Avoid calling progressbar events on CoreNEURON execution

### CODE REVIEW

**Comment by pramodk** [comment]
this could be merged @iomaganaris now?

**Comment by iomaganaris** [comment]
I updated this branch with one option missing to run the NEURON paper's scripts. One thing missing from the paper's branch is this:
```
runsim.build_part_model(range(0, 120), [])
```
Setting the model size. Do you think that this needs to be merged to the `2to3` branch and then `master`?

**Comment by pramodk** [comment]
> One thing missing from the paper's branch is this:

I don't think we should/need to add paper specific code (i.e. model size) here. This will be general purpose model repository. 

If we need exact thing for the paper, there can be a branch with minor changes like this? 🤔

**Review by pramodk — APPROVED** [review]
LGTM.

**Comment by iomaganaris** [comment]
> > One thing missing from the paper's branch is this:
> 
> I don't think we should/need to add paper specific code (i.e. model size) here. This will be general purpose model repository.
> 
> If we need exact thing for the paper, there can be a branch with minor changes like this? thinking

I believe so. Then this PR is ready to merge

**Pull request merged**
