### PR TITLE
Python 2 to Python 3 Migration

### PR DESCRIPTION
**Pull request by nrnhines**
2to3 along with minor bug fix. I suspect the effect of randomness will be different because of different ordering of dictionary iteration between python 2 and 3. Also the 2to3 tends to add list(...) around iterators which are not always needed for python3.
The use of MGRS.slot should be reviewed as it has changed from integer to apparently a location tuple. I believe the original slot
was introduced because of the possibility (perhaps never realized) of multiple connections with same 6 tuple definition. And that was substantively used with ```def mgrs_gid(gid_source, gid_target, slot=0):```. This def does not exist in this repository.

### CODE REVIEW

**Comment by pramodk** [comment]
@nrnhines : thank you! I  will test this tomorrow but asking in advance : I assume the code is python2 as well as python3 compatible, right?

**Comment by nrnhines** [comment]
I haven't checked python2 compatibility.  Print will occasionally produce a tuple now instead of just the contents but that is not important. It will be a simple matter to otherwise make it compatible and even the print can be the same with a bit of tedious work.

**Comment by nrnhines** [comment]
The biggest problem will be to get quantitative identity as that is likely to involve a serious review of the use of randomness with respect to deciding whether a synapse is to be created or not. That was an issue even with python2 due to the nhost dependence of randomness. i.e. imagine choosing 100 items from a pool of 1000 without replacement in parallel.

**Comment by pramodk** [comment]
@mmigliore : someone from your team will have time to verify the results after switching this model to Python3?

**Comment by EmilianoSpera** [comment]
@pramodk about verifing the results after switching the model to Python 3, I tried to install the olfactory bulb model on marconi 100, but I received the following error message  "Unable to locate a modulefile for 'pgi/19.10--binary' "

**Comment by pramodk** [comment]
@EmilianoSpera : most likely module names are changed. I will take a look and update the README tomorrow. Thank you!

**Comment by pramodk** [comment]
@EmilianoSpera : I was looking on Marconi100 and see that GPU compiler module version is now changed. I can fix that quickly but I just realised that for this specific ticket we just want to verify python2 vs python3 results. So let's first compare just Python2 vs Python3 aspects with NEURON on CPU (not necessary to check GPU because results will be same as CPU version).

To test python2 vs Python3 you can do following:


1. Clone repo : 

```
git clone https://github.com/HumanBrainProject/olfactory-bulb-3d.git
cd olfactory-bulb-3d/sim
```

2. For testing Python3 installation : 

First checkout this PR branch:

```
git checkout 2to3
```

Load necessary modules and compile mod files:
```
module purge
module load profile/advanced
module load gnu/8.4.0 anaconda/2020.02
module load spectrum_mpi/10.3.1--binary boost/1.72.0--spectrum_mpi--10.3.1--binary
export OMPI_CXX=g++
export OMPI_CC=gcc
export CC=mpicc
export CXX=mpicxx

rm -rf ppc64le
/m100_work/Pra18_4575_0/software/cpu/install-python3/bin/nrnivmodl -loadflags "-ldl" .
```

Create your job script and run the model: Below are just sample scripts. Adjust number of nodes and parameters in bulb3dtest.py as required.

```
#!/bin/bash
#SBATCH -A Pra18_4575_0
#SBATCH -p m100_usr_prod
#SBATCH --time 00:60:00
#SBATCH --ntasks-per-node=64
#SBATCH --job-name=neuron_cpu_test
#SBATCH --nodes=2

module purge
module load profile/advanced
module load gnu/8.4.0 anaconda/2020.02
module load spectrum_mpi/10.3.1--binary

export PYTHONPATH=/m100_work/Pra18_4575_0/software/cpu/install-python3/lib/python/:$PYTHONPATH
mpirun ./ppc64le/special -python -mpi bulb3dtest.py
```


3. For testing Python 2

First checkout master branch:

```
git checkout master
```

Load necessary modules and compile mod files:

```
module purge
module load profile/advanced
module load gnu/8.4.0
module load spectrum_mpi/10.3.1--binary boost/1.72.0--spectrum_mpi--10.3.1--binary
export OMPI_CXX=g++
export OMPI_CC=gcc
export CC=mpicc
export CXX=mpicxx

rm -rf ppc64le
/m100_work/Pra18_4575_0/software/cpu/install-python2/bin/nrnivmodl -loadflags "-ldl" .
```

Create your job script and run the model: Below are just sample scripts. Adjust number of nodes and parameters in bulb3dtest.py as required.


```
#!/bin/bash
#SBATCH -A Pra18_4575_0
#SBATCH -p m100_usr_prod
#SBATCH --time 00:60:00
#SBATCH --ntasks-per-node=64
#SBATCH --job-name=neuron_cpu_test
#SBATCH --nodes=2

module purge
module load profile/advanced
module load gnu/8.4.0
module load spectrum_mpi/10.3.1--binary

export PYTHONPATH=/m100_work/Pra18_4575_0/software/cpu/install-python2/lib64/python/:$PYTHONPATH
mpirun ./ppc64le/special -python -mpi bulb3dtest.py
```

Let me know if you need any information.

**Comment by pramodk** [comment]
@EmilianoSpera : did you get chance to test above instructions? let me know if any help is needed. Thank you!

**Comment by EmilianoSpera** [comment]
@pramodk   I tested the  instructions that you attached above to compare Python2 and Python3 version of bulb code, but both the jobs return the follow error: 
"./ppc64le/special: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory"

Do you have any suggestion to solve this problem?

**Comment by pramodk** [comment]
Hello @EmilianoSpera,

In the meantime, the libraries/modules must have changed on Marconi 100. I will get re-compile NEURON and update instructions by tomorrow.

**Comment by pramodk** [comment]
@mmigliore  @EmilianoSpera,

If I am not mistaken, the project `Pra18_4575_0` is expiring end of this month and we still have CPU time quota:

```
[pkumbhar@login01 sim]$ saldo -b
-----------------------------------------------------------------------------------------------------------------------------------------
account                start         end         total        localCluster   totConsumed     totConsumed     monthTotal     monthConsumed
                                             (local h)   Consumed(local h)     (local h)               %      (local h)         (local h)
-----------------------------------------------------------------------------------------------------------------------------------------
Pra18_4575_0        20190402    20210430       1315156                4084          4084             0.3         51982                 10
```

But when I try to allocate job, it gets `qos_lowprio` and hence I assume I have to wait too long even to get single node allocation for debugging:

```
[pkumbhar@login01 sim]$ salloc -N1 --exclusive --gres=gpu:4 -A Pra18_4575_0 -p m100_usr_prod --time=01:00:00
salloc: qos_lowprio assigned to job
salloc: Pending job allocation 2833798
salloc: job 2833798 queued and waiting for resources
```
Am I using wrong parameters? Or, anything else I need to change?

In the [docs](https://wiki.u-gov.it/confluence/pages/viewpage.action?pageId=336727645#UG3.2:MARCONI100UserGuide-Interactive) I can only see:

```
Users with exhausted but still active projects are allowed to keep using the cluster resources, even if at a very low priority, by adding the  "qos_lowprio" flag to their job:
#SBATCH --qos=qos_lowprio

This QOS is automatically associated to Eurofusion users once their projects exhaust the budget before their expiry date. For all the other users, please ask superc@cineca.it the QOS association.

Eurofusion users can also use the computing resources at low priority before their budget gets exhausted, in case they wish to run non urgent jobs without consuming the budget of the granted project. Please ask superc@cineca.it to be added to the Account FUAC4_LOWPRIO, and specify this account and the qos_lowprio QOS in your submission script. 
```

**Comment by mmigliore** [comment]
Hi Pramod,
you can use the default queue until Apr.30.
Michele

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by pramodk** [comment]
@mmigliore : I am using default queue i.e. `-p m100_usr_prod`. Is anyone else actively using Marconi100 from the same project `Pra18_4575_0`? Otherwise, I can quickly clarify this with helpdesk.

**Comment by mmigliore** [comment]
Emiliano is opening a ticket on this right now.
I told him to put you in cc.
Best
Michele

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by pramodk** [comment]
@mmigliore @EmilianoSpera : Considering above response from Helpdesk, I am not sure what is best strategy. I have submitted 2 nodes job yesterday morning and it's still pending:

```
$ squeue -u $USER
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
           2833610 m100_usr_ neuron_c pkumbhar PD       0:00      2 (Priority)
```

For this specific ticket of Python2 vs Python3, we can do this test/validation on any other machine.

@EmilianoSpera : which other machines you have access to? We can have a skype/zoom call together and make sure you have working installation of Python2 and Python3. Then you can validate this pull request and we can get this merged.

For Marconi100, if we don't get jobs allocation faster then I am not sure how we can use allocation?

**Comment by mmigliore** [comment]
Hi Pramod,

I told this to Cineca management, and they promised to look into it.
We were supposed to be able to use the normal queue. We will eventually get
full access on this machine. So, I guess we should look somewhere else for
now.

We have computing time on the cscs CPU (ich035m) and GPU (ich035)
partition.
You should already have access to it.
We also have time on JUSUF (icei-hbp-2020-0013).
Emiliano can access any of these.

Let us know which one you prefer for the tests.
Best
Michele


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by pramodk** [comment]
> I told this to Cineca management, and they promised to look into it.
> We were supposed to be able to use the normal queue. We will eventually get
> full access on this machine. So, I guess we should look somewhere else for
> now.

Ok, understood. 👍 

> We have computing time on the cscs CPU (ich035m) and GPU (ich035) partition.

Ok. I have setup NEURON installation with Python2 / Python3 on Piz-Daint.

Sample job scripts for Python2 and Python3 are here:

```
Python 2 : /store/hbp/ich035/kumbhar/sim/job_python2.sh
Python 3 : /store/hbp/ich035/kumbhar/sim/job_python3.sh
```

@EmilianoSpera : note that above job script clone this olfactory-bulb-3d repository, compile mod files and run the model.
Please change the model parameters as necessary. Based on the model size, also change number of nodes required in the job script accordingly.

If you will have any questions, let me know.

**Comment by EmilianoSpera** [comment]
Hi @pramodk , I tested the python2 and python3 codes with the same network configuration and the same input data but the outputs were different. 
For example the bulb3dtest.weight files are different both in terms of GID and weights.

**Comment by EmilianoSpera** [comment]
Hi @pramodk, if you need to check the simulations results you find them on the following paths:

/users/bp000245/python2/olfactory-bulb-3d/sim/
/users/bp000245/python3/olfactory-bulb-3d/sim/

**Comment by pramodk** [comment]
@EmilianoSpera : I probably won't be able to judge the differences in the results. May be @nrnhines and @mmigliore can take a look at it?

**Comment by nrnhines** [comment]
I haven't looked at the results but, given the randomness issue and the dictionary order issue, it will be best to begin with a smaller model that can be run on a single process on one's desktop. @mmigliore we can discuss and make a judgement about whether the python 2 and 3 results are equally reliable and if the differences are substantive. It probably is possible to force the effect of dictionary order to be the same for 2 and 3. In which case, if I am right about the randomness issue, the results on a single process should be the same for 2 and 3.
> That was an issue even with python2 due to the nhost dependence of randomness

Do you notice different results for different nhost even if both runs are using python2. If so the most we can hope for by forcing same dictionary order is same results for 2 and 3 only if both are running with same nhost. But at the moment this is just speculation and would have to be tested.

**Comment by nrnhines** [comment]
@pramodk There is presently a trivial conflict in README.md
```
<<<<<<< 2to3
Make sure you have neuron with Python3 installed (or neuron module loaded). You can then compile mod files as:
=======
NEURON+CoreNEURON has been already installed at below location on Marconi100:
>>>>>>> master
```
I'd accept the master but there is no mention of Python3. Is that now the default?  Or is it something one needs to be told about
when using marconi? (perhaps by adding a module load statement?)

**Comment by mmigliore** [comment]
I'll check the results with the visualization later today.

Il ven 30 apr 2021, 11:53 nrnhines ***@***.***> ha scritto:

**Comment by pramodk** [comment]
> I'd accept the master but there is no mention of Python3. Is that now the default? Or is it something one needs to be told about when using marconi? (perhaps by adding a module load statement?)

@nrnhines : go ahead with accepting master. This needs to be changed anyway.

**Comment by mmigliore** [comment]
I visualized the synaptic weights for mitral cell 160, and selected one
compartment, in green in the figure below.
The two red cells are the granule cells connected to that compartment.
python2 results are on the left, python3 on the right. As you see the
results are significantly different.
[image: image.png]
Because the number and location of potentiated granule cells (in green) is
approximately the same we can live with that, although it means that past
simulations will not be reproducible anymore.
However, we must be sure that a simulation with python3 carried out on a
different number of processors give identical results.
Michele

**Comment by mmigliore** [comment]
The image was not loaded with my previous comment. Here is it.
image

**Comment by nrnhines** [comment]
My speculations about differences being due to dictionary order between python2.7 and 3.9 and nhost differences with regard to random sampling without replacement are still alive with the following setup results. In every case all numbers are the same (# mitrals = 75, # connections = 72182) but the number of granules differ. I.e.
python3.9 2to3 branch 1 rank  ngranule = 46701
python3.9 2to3 branch 6 rank  ngranule = 46830
python2.7 master          1 rank ngranule = 46757
python2.7 master          6 rank ngranule = 46656

I'll pursue this further with goal of a 2to3 branch that can run both 3.9 and 2.7 and in all 4 cases, generate the same ngranule.

**Comment by nrnhines** [comment]
So far it appears that dict order does not modify results.  I branched odict off the master and replaced all {} with odict() which returns a collections.OrderedDict(). That gives the same number of granules, 46656, for python2.7 master 6 rank as above.

**Comment by pramodk** [comment]
@nrnhines : this is a long pending but wasn't sure if your last comment was conclusive. Is this now ready?

**Comment by nrnhines** [comment]
The last comment suggests that my hypothesis that dictionary order is the reason of python2 and 3 differences is incorrect.
So the problem is still open. However the first step would be to see if python2 and python3 in fact give different results for this model.

**Comment by clupascu** [comment]
Hi @nrnhines and @pramodk,

@EmilianoSpera will handover the test of this issue to me. Please let me know if I should test again the python2 and python3 versions.

Thank you,
Carmen

**Comment by nrnhines** [comment]
@clupascu I think we should begin with a single process small model (one or two glomeruli with fewer mitrals per glomerulus) that is runable on a desktop and verify identity between python2 and python3. As support for python2 has been removed, it may be best to use Release 8.0.0

**Comment by pramodk** [comment]
@clupascu : this is quite old thread but it will be great to get this todo done. What would be easiest for you to test this? Should I install this version with neuron+python2 and neuron+python3 on the system like Piz-Daint and then you can run tests & compare results? Or any other machine? If you prefer to work Desktop, I can also write detailed instructions or help to setup this as well.

**Comment by mmigliore** [comment]
Please pass everything related to the olfactory bub model to Joao.
Best
Michele

**Review by pramodk — APPROVED** [review]
LGTM

**Pull request merged**
